

apiVersion: wso2.com/v1beta1
kind: API
metadata:
  name: bar-api
  namespace: wso2
spec:
  definition-cf-name: swagger-cf-bar
  APIData:
    description: This is a simple API for Pizza Shack online pizza delivery store.
    context: /pizzashack
    version: 1.0.0
    provider: admin
    lifeCycleStatus: PUBLISHED
    enableSchemaValidation: false
    type: HTTP
    transport:
    - http
    - https
    tags:
    - pizza
    policies:
    - Unlimited
    authorizationHeader: Authorization
    securityScheme:
    - oauth2
    - oauth_basic_auth_api_key_mandatory
    visibility: PUBLIC
    visibleRoles: []
    visibleTenants: []
    subscriptionAvailability: CURRENT_TENANT
    subscriptionAvailableTenants: []
    additionalProperties: []
    additionalPropertiesMap: {}
    accessControl: NONE
    accessControlRoles: []
    businessInformation:
      businessOwner: Jane Roe
      businessOwnerEmail: marketing@pizzashack.com
      technicalOwner: John Doe
      technicalOwnerEmail: architecture@pizzashack.com
    corsConfiguration:
      corsConfigurationEnabled: false
      accessControlAllowOrigins:
      - '*'
      accessControlAllowCredentials: false
      accessControlAllowHeaders:
      - authorization
      - Access-Control-Allow-Origin
      - Content-Type
      - SOAPAction
      - apikey
      - Internal-Key
      accessControlAllowMethods:
      - GET
      - PUT
      - POST
      - DELETE
      - PATCH
      - OPTIONS
    scopes: []
    categories: []
    keyManagers:
    - all
    advertiseInfo:
      advertised: false
      apiOwner: admin
      vendor: WSO2
    gatewayVendor: wso2
    gatewayType: wso2/synapse
    asyncTransportProtocols: []
    organizationId: carbon.super
